version: '3.8'

services:
  telegram-linux-python:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      - SUDO_PASSWORD=${SUDO_PASSWORD:-}
      - PORT=3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.25'

networks:
  app-network:
    driver: bridge
